version: '2.1'

services:
  vue-cosmosdb:
    image: vue-cosmosdb
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3001:3001
      - 9229:9229
    command: node --inspect index.js